# Generated by Django 2.1.3 on 2019-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='buildExist',
            field=models.BooleanField(default=False),
        ),
    ]
