# Generated by Django 2.1.3 on 2019-04-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0002_building_buildexist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('destination', models.CharField(max_length=100)),
                ('roomNo', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('directions', models.TextField(verbose_name='Directions')),
                ('buildID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bps.Building')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routes',
            unique_together={('buildID', 'roomNo')},
        ),
    ]
