# Generated by Django 2.1.3 on 2019-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0003_auto_20190130_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floorImageLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
