# Generated by Django 2.1.3 on 2019-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0004_floor_floorimagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floorImageLink',
            field=models.URLField(),
        ),
    ]
