# Generated by Django 2.1.3 on 2019-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0005_auto_20190218_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floorImageLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
