# Generated by Django 2.1.3 on 2019-02-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0006_auto_20190218_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='buildFloors',
            field=models.IntegerField(default=1),
        ),
    ]
