# Generated by Django 2.1.3 on 2019-02-22 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0007_building_buildfloors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floorID',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
