# Generated by Django 2.1.3 on 2019-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bps', '0009_auto_20190222_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('buildID', 'floorID')},
        ),
    ]
