# Generated by Django 2.1.3 on 2018-12-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Trip'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Passenger'),
        ),
    ]
