# Generated by Django 2.1.3 on 2018-12-02 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_driver',
            name='busID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Bus'),
        ),
        migrations.AlterField(
            model_name='bus_driver',
            name='driverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Driver'),
        ),
        migrations.AlterField(
            model_name='bus_trip',
            name='busID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Bus'),
        ),
        migrations.AlterField(
            model_name='bus_trip',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Trip'),
        ),
        migrations.AlterField(
            model_name='currentterminal',
            name='terminalID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Terminal'),
        ),
        migrations.AlterField(
            model_name='currentterminal',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Trip'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='tripID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Trip'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Passenger'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destinationTerminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinationTerminal', to='tickets.Terminal'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='sourceTerminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceTerminal', to='tickets.Terminal'),
        ),
    ]
